add post table
maulanaadil/Market-post pull request #15
Opened 2022-07-22 08:43 UTC by adityasuryana

Pagination nya belum dibuat

![image](https://user-images.githubusercontent.com/44171476/180400632-cb2cee6b-8a32-4059-9046-ba6fab03f693.png)

2022-07-22 08:45 UTC, ichsnn commented
aku lanjutin dulu

2022-07-24 11:40 UTC, maulanaadil requested changes

2022-07-24 11:40 UTC, maulanaadil commented on src/modules/post-table/index.jsx
> +                  status={post.status}
Klo dari design si masing2 status ada warnanya, coba cek lagi design figmanya
![image](https://user-images.githubusercontent.com/59109741/180645174-85b9f002-d223-4829-976c-8637a10b3055.png)

aku saranin ada 3 status:
- published (ijo)
- drafted (kuning)
- scheduled (original color)

2022-07-24 11:40 UTC, maulanaadil commented on src/modules/post-table/index.jsx
> +            <FilterButton filterType={'All'} label={'Post status: '} />
ini di pisahin aja componentnya, soalnya buat page ini khusus buat component table doang.

2022-07-24 11:40 UTC, maulanaadil commented on src/modules/post-table/index.jsx
> +            <FilterButton filterType={'Latest'} label={'Post time: '} />
Ini juga sama

2022-07-24 11:40 UTC, maulanaadil commented on src/modules/post-table/index.jsx
> +            <SearchButton placeholder={'Search feeds'} />
Ini juga sama

2022-07-24 12:07 UTC, maulanaadil commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard Home Page](https://trello.com/c/3loY0vJI/60-dashboard-home-page)

2022-07-24 14:52 UTC, merged