implement calendar component
maulanaadil/Market-post pull request #19
Opened 2022-07-22 15:38 UTC by ichsnn

[NOTE] + react-calendar [](https://github.com/wojtekmaj/react-calendar)

<img width="244" alt="image" src="https://user-images.githubusercontent.com/72180474/180474211-333a26f8-934b-46b6-826c-dcb85c1d774e.png">

2022-07-24 08:10 UTC, maulanaadil approved these changes

2022-07-24 09:00 UTC, maulanaadil requested changes

2022-07-24 09:00 UTC, maulanaadil commented on src/pages/home/index.jsx
> +import CalendarTime from '../../modules/sidebar-create-post/components/calendar-time';
ini import nya jangan gini euy, samain importnya kayak line 2.

2022-07-24 09:02 UTC, maulanaadil commented on src/pages/home/index.jsx
> +        <CalendarTime />
Panggil calendarnya pas di bagian sidebar create post, jangan di home wkwkw
![image](https://user-images.githubusercontent.com/59109741/180640058-0b66b613-99ee-4797-ad1b-f90cfef3390b.png)

2022-07-24 09:24 UTC, ichsnn commented on src/pages/home/index.jsx
> +        <CalendarTime />
belum dilanjut itu kang wkwkwk

2022-07-24 11:53 UTC, maulanaadil commented on src/pages/home/index.jsx
> +        <CalendarTime />
woalah oke oke sok

2022-07-25 03:35 UTC, ichsnn commented
<img width="432" alt="image" src="https://user-images.githubusercontent.com/72180474/180694038-cb2ca5ba-4c41-4349-a391-64536c176b83.png">

2022-07-25 07:16 UTC, ichsnn reviewed
test

2022-07-25 07:16 UTC, ichsnn reviewed
test

2022-07-25 09:07 UTC, maulanaadil requested changes

2022-07-25 09:13 UTC, maulanaadil approved these changes

2022-07-25 09:13 UTC, merged